# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  host: 'localhost'
  username: 'postgres'
  password: 'postgres'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ruby_dev_test_1_development

test:
  <<: *default
  database: ruby_dev_test_1_test
